services:
  db:
    container_name: embed_db
    image: ankane/pgvector
    ports:
      - 8504:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=ai_user
      - POSTGRES_DB=ai_db
